name: Common CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: common-${{ github.ref }}
  cancel-in-progress: true

jobs:
  connected-android-test:
    runs-on: macOS-11
    timeout-minutes: 60
    
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        include:
          - api-level: 29
            target: default
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Android SDK License
        run: (while sleep 3; do echo "y"; done) | /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build tests
        run: ./gradlew :common:assembleAndroidTest

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2.20.0
        timeout-minutes: 40
        with:
          api-level: ${{ matrix.api-level }}
          profile: Nexus 6
          target: ${{ matrix.target }}
          script:  |
            adb logcat > logcat.txt &
            ./gradlew :common:connectedCheck

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.api-level }}-${{ matrix.target }}
          path: logcat.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.api-level }}-${{ matrix.target }}
          path: "**/build/outputs/**/connected/**/*.xml"
